### ISSUE TITLE
Limited to 50 playlist?

### ISSUE THREAD

**Issue by Eric-sson** [Gyarbij/Plexist#24]
Is it a known issue that the script stops after 50 playlists?
I have more liked playlists in spotify but looks like it just stops after the 1st 50 playlists.

**Comment by Gyarbij** [comment]
Hi, it's not the expected behavior and unknown to me as it didn't do that previously.

When did you start to experience this? 

It's currently fine on the Deezer side and it was on Spotify as that's where I was before switching to Deezer and I also have a few hundred playlist.

**Comment by Eric-sson** [comment]
I just run it today and noticed it only created the 1st 50 playlist I have in my library of spotify. 
Will give it a try with Deezer to see if it will continue after 50.

**Comment by Gyarbij** [comment]
Let me know if you run into the same issue there and I'll have a look at Spotify next week to see if I can reproduce the error.

**Comment by Eric-sson** [comment]
I liked 100 playlists on Deezer and let the script run. All 100 playlists are created in my Plex library.
From what I could see in another project this might be a limitation of the Spotify API which makes it stop after 50 playlists.

**Comment by Gyarbij** [comment]
> I liked 100 playlists on Deezer and let the script run. All 100 playlists are created in my Plex library. From what I could see in another project this might be a limitation of the Spotify API which makes it stop after 50 playlists.

Thanks for the follow up, for now i'm going to mark it as a bug and see if there is anything that can be done on my end.

**Comment by Eric-sson** [comment]
I found this pull request in another project. I am not a coder myself but maybe it can give you some pointers on how to work around the limitations.

https://github.com/rnagabhyrava/plex-playlist-sync/pull/53

**Comment by Gyarbij** [comment]
> 

Hey, thanks for the patience and the PR, I haven't taken that one in as I had an update that i'll like you to test. it's available at : 

gyarbij/plexist:dev

Let me know if it pulls more than 50 and you can find the changelog on the dev branch.

**Comment by Eric-sson** [comment]
I let it run a few times with mixed results. The error I saw the 1st run was a timeout to the plex server. Yesterday I let it run again and it created 194 playlist. Looks like it improved a lot. Latest message in the log is that I completed the Deezer playlist sync.
