### ISSUE TITLE
Cannot write CSV

### ISSUE THREAD

**Issue by l0k3n** [Gyarbij/Plexist#41]
I dont know what I'm doing wrong, but i cannot get it to write missing tracks to a csv.  Both with docker and and native.  With docker i mounted a volume for data and wouldn't work.  With Python I wrote a direct path to save it.  Ive gotten as far as it creating the empty file, but it wont write the tracks to it.  They all give me permission issues.

**Comment by Gyarbij** [comment]
Do you have an logs?

**Comment by l0k3n** [comment]
The only thing it shows at the moment is: "log":"INFO:root:Failed to write missing tracks for Take it Slow, likely permission issue\n"

Where Take it Slow is the name of the playlist

**Comment by Gyarbij** [comment]
Well i'm a year late getting back to this but can you check the current dev branch to see if you're still getting the issue, additional you can try setting GUID and PID if you're using docker compose.
