### ISSUE TITLE
Plexist exits out halfway through first playlist. 

### ISSUE THREAD

**Issue by edster** [Gyarbij/Plexist#53]
**Describe the bug**
Plexist will start running and I can see in the logs it's syncing. I can see the first playlist in plex. When it gets around halfway through that first playlist it just exits though. No error in logs, just stops running. 

I'm syncing with Spotify. 

**Desktop (please complete the following information):**
 - OS: docker on unraid.

**Comment by Gyarbij** [comment]
Can you try the current `dev` tag and let me know if you're still getting that issue as well as any logs from the docker output.

**Comment by edster** [comment]
Yea I'll try to grab them this week!

**Comment by Gyarbij** [comment]
Thanks, the :latest tag is now updated. If the error is like what i encountered it's the plex rate limit and i've implemented a retry mechanism to address it. It will throw an error when it encounters it now but should continue to function. if it's critical, it will fail and restart but should pick up from the cache (new) instead if from the beginning.

**Comment by edster** [comment]
Great, I it looks like it was only failing on certain playlists.

Will be checking this week

**Comment by edster** [comment]
Attempted to use your test tag. Looks like you may have a typo: See PR. https://github.com/Gyarbij/Plexist/pull/68

**Comment by edster** [comment]
Realized you asked me to use latest and not test. I'm getting a plex authorization error with this tag, got to see what that is about as I wasn't getting it with the core docker release.

`ERROR:root:Plex Authorization error: (401) unauthorized; http://{MYIP:PORT}/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>`

**Comment by Gyarbij** [comment]
Thanks for the PR and can you try grabbing a new token? 

I did not encounter that particular bug because I wasn't updating against my old install when working on it again but it was a fresh setup.

So i'm hoping a new Plex token would solve that for you.

**Comment by edster** [comment]
grabbed a new token and was able to sync! woot!

**Comment by edster** [comment]
I just realized you might have not wanted to close this as it was a separate tag xD
